### ISSUE TITLE
[Bug Report] gcat you borked it

### ISSUE THREAD

**Issue by tizu69** [Modern-Modpacks/mm-upptime#245]
**Describe the bug**
idfk ur ci is failing, no updates

**To Reproduce**
1. Go to 'repo'
2. Click on 'README.md'
3. Scroll down to 'badges'

**Expected behavior**

anything but this

**Screenshots**
![image](https://github.com/user-attachments/assets/395e9188-d0a6-4653-b1ed-3c03a8878222)

**Desktop (please complete the following information):**
 - OS: Void x86_64 (Kernel 6.6.44_1)
 - Browser: Firefox
 - Version: 6

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 Pro
 - OS: Evolution X
 - Browser: Chrome
 - Version: of what

**Additional context**
@Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101 @Gcat101

**Comment by Gcat101** [comment]
I did not break shit, this was [upptime's problem](https://github.com/upptime/upptime/issues/800) and you should shut the fuck up

**Comment by Gcat101** [comment]
not fixed

**Comment by tizu69** [comment]
i blame you for using upptime in the first place :3

**Comment by Gcat101** [comment]
fixed
